### PR TITLE
Added accumulate.md

### PR DESCRIPTION
**Pull request by harshraj22**
Added accumulate.md displaying the use of std::accumulate from algorithms library.

### CODE REVIEW

**Comment by Bhupesh-V** [comment]
@harshraj22 I am not sure what are you trying to contribute.
Is it a code snippet (if it is then rename the file to `.cpp` and move the file to snippets directory).
If not see how the format of other `.md` files

**Comment by harshraj22** [comment]
@Bhupesh-V Done as instructed.
P.S. I am quite new to git and learning how to contribute to open-source. Hope you don't mind my small mistakes :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by Bhupesh-V** [comment]
@harshraj22 No worries :smiley: 
Also could you make the description a little brief, so it's easier to understand

**Comment by harshraj22** [comment]
@Bhupesh-V Done.

**Comment by Bhupesh-V** [comment]
Would you like to create a Markdown based function description of accumulate too.
See this [example](https://github.com/Bhupesh-V/30-seconds-of-cpp/blob/master/algorithm/for_each_n.md).
Copy the format from the CONTRIBUTING file

**Pull request merged**
