### PR TITLE
Added push_back.md in vector header and push_back.cpp in snippets

### PR DESCRIPTION
**Pull request by kamalbhardwaj**

### CODE REVIEW

**Comment by manav1234** [comment]
i believe that you have added a space in the file name try removing the space 
change 
# push_back.md
to 
#pushback.md

**Comment by manav1234** [comment]
i think underscores are not allowed in markdown fiile names

**Comment by manav1234** [comment]
also Mr Kamal please close this pr

**Comment by Bhupesh-V** [comment]
Thank you for your contribution @kamalbhardwaj  :+1: 
:relaxed: :relaxed: :relaxed:

**Pull request merged**
